/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppQuitConfirm: typeof import('./components/AppQuitConfirm.vue')['default']
    AudioPlayer: typeof import('./components/common/AudioPlayer.vue')['default']
    CodeViewerDialog: typeof import('./components/common/CodeViewerDialog.vue')['default']
    DataConfigDialogButton: typeof import('./components/common/DataConfigDialogButton.vue')['default']
    DragPasteContainer: typeof import('./components/common/DragPasteContainer.vue')['default']
    FeedbackTicketButton: typeof import('./components/common/FeedbackTicketButton.vue')['default']
    FileExt: typeof import('./components/common/FileExt.vue')['default']
    FileLogViewer: typeof import('./components/common/FileLogViewer.vue')['default']
    FilesSelector: typeof import('./components/common/FilesSelector.vue')['default']
    HtmlViewer: typeof import('./components/common/HtmlViewer.vue')['default']
    IMdiAndroid: typeof import('~icons/mdi/android')['default']
    IMdiCast: typeof import('~icons/mdi/cast')['default']
    IMdiUsb: typeof import('~icons/mdi/usb')['default']
    IMdiVideo: typeof import('~icons/mdi/video')['default']
    IMdiWifi: typeof import('~icons/mdi/wifi')['default']
    InputInlineEditor: typeof import('./components/common/InputInlineEditor.vue')['default']
    LogViewer: typeof import('./components/common/LogViewer.vue')['default']
    LogViewerDialog: typeof import('./components/common/LogViewerDialog.vue')['default']
    MEmpty: typeof import('./components/common/MEmpty.vue')['default']
    MLoading: typeof import('./components/common/MLoading.vue')['default']
    PageNav: typeof import('./components/PageNav.vue')['default']
    PageWebviewStatus: typeof import('./components/common/PageWebviewStatus.vue')['default']
    ProUpgrade: typeof import('./components/common/ProUpgrade.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingAbout: typeof import('./components/Setting/SettingAbout.vue')['default']
    SettingBasic: typeof import('./components/Setting/SettingBasic.vue')['default']
    SettingEnv: typeof import('./components/Setting/SettingEnv.vue')['default']
    SettingEnvHubRoot: typeof import('./components/Setting/components/SettingEnvHubRoot.vue')['default']
    SettingItemInput: typeof import('./components/common/SettingItemInput.vue')['default']
    SettingItemYesNo: typeof import('./components/common/SettingItemYesNo.vue')['default']
    SettingItemYesNoDefault: typeof import('./components/common/SettingItemYesNoDefault.vue')['default']
    TaskBizStatus: typeof import('./components/common/TaskBizStatus.vue')['default']
    TextTruncateView: typeof import('./components/TextTruncateView.vue')['default']
    UpdaterButton: typeof import('./components/common/UpdaterButton.vue')['default']
    VideoPlayer: typeof import('./components/common/VideoPlayer.vue')['default']
    WebFileSelectButton: typeof import('./components/common/WebFileSelectButton.vue')['default']
  }
}
